version: "3.8"

services:
  db:
    image: postgres:15
    container_name: edge_tree_db
    environment:
      POSTGRES_DB: prewave_edge_tree_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d

  jooq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edge_tree_jooq_gen
    depends_on:
      - db
    entrypoint: [ "./gradlew", "generateJooq", "--no-daemon" ]
    environment:
      JOOQ_JDBC_URL: jdbc:postgresql://db:5432/prewave_edge_tree_db
      JOOQ_JDBC_USER: postgres
      JOOQ_JDBC_PASSWORD: postgres123

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edge_tree_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: swagger
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/prewave_edge_tree_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
    depends_on:
      - db
      - jooq

volumes:
  db_data: